<#
.SYNOPSIS
    ApplyLoop installer for Windows 10/11.

.DESCRIPTION
    PowerShell port of install.sh. Handles activation, dependency bootstrap
    (winget for Python/Node/Git, npm for openclaw + claude-code), repo clone,
    venv setup, UI build, cloud config fetch, profile.json + .env generation,
    .exe build, CLI shim, and Task Scheduler auto-update job.

.USAGE
    Recommended one-liner (run in an elevated PowerShell window):
        irm https://applyloop.vercel.app/install.ps1 | iex

    With activation code via env var:
        $env:APPLYLOOP_CODE = "AL-XXXX-XXXX"; irm https://applyloop.vercel.app/install.ps1 | iex

    Or download and run manually:
        iwr https://applyloop.vercel.app/install.ps1 -OutFile install.ps1
        .\install.ps1 -Code AL-XXXX-XXXX

.NOTES
    Requires Windows 10 1809+ (for ConPTY/winget).
    Mirrors install.sh feature-for-feature where possible.
#>
[CmdletBinding()]
param(
    [string]$Code = "",
    [string]$Branch = "main",
    [string]$RepoUrl = "https://github.com/snehitvaddi/ApplyLoop",
    # Skip the full install path; only regenerate the CLI shim + fallback
    # aliases from the already-cloned repo. Used by update.ps1 to self-heal
    # an older or broken applyloop.cmd without re-running the full install.
    [switch]$ShimRefreshOnly
)

$ErrorActionPreference = "Stop"

# ─── Logging helpers ────────────────────────────────────────────────────────
function Write-Log    ($msg) { Write-Host "[applyloop] $msg" -ForegroundColor Cyan }
function Write-Warn   ($msg) { Write-Host "[applyloop] WARN: $msg" -ForegroundColor Yellow }
function Write-Err    ($msg) { Write-Host "[applyloop] ERROR: $msg" -ForegroundColor Red }
function Die          ($msg) { Write-Err $msg; exit 1 }

# ─── BOM-less UTF-8 file writer ─────────────────────────────────────────────
# Windows PowerShell 5.1's `Set-Content -Encoding UTF8` writes files with a
# 3-byte UTF-8 BOM (EF BB BF). Python reads on Windows default to cp1252,
# which decodes those BOM bytes as 3 high-ordinal characters and then chokes
# when the value gets passed to httpx as an HTTP header value or to json.load.
# Use the .NET UTF8Encoding with $false (no BOM) to match Mac install.sh.
function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory=$true)] [string]$Path,
        [Parameter(Mandatory=$true)] [string]$Content
    )
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

# ─── Native-command runner immune to PowerShell's stderr-is-fatal trap ─────
# With $ErrorActionPreference = "Stop", PowerShell escalates ANY stderr
# output from a native command (npm warnings, schtasks chatter, deprecation
# notices) into a terminating exception — even when stderr is redirected
# with 2>&1 | Out-Null. cmd /c bypasses this because the called process's
# stderr stays inside cmd's process boundary and never crosses back into
# PowerShell's error stream. Use this wrapper for any external CLI whose
# stderr is chatty but non-fatal (npm, schtasks, winget warnings, etc.).
function Invoke-Native {
    param(
        [Parameter(Mandatory=$true)] [string]$Command,
        [string]$Description = ""
    )
    if ($Description) { Write-Log $Description }
    cmd /c $Command 2>$null | Out-Null
    return $LASTEXITCODE
}

# ─── Constants ──────────────────────────────────────────────────────────────
$AppUrl         = if ($env:NEXT_PUBLIC_APP_URL) { $env:NEXT_PUBLIC_APP_URL } else { "https://applyloop.vercel.app" }
$ApplyloopHome  = if ($env:APPLYLOOP_HOME) { $env:APPLYLOOP_HOME } else { Join-Path $env:USERPROFILE ".applyloop" }
$WorkspaceDir   = Join-Path $env:USERPROFILE ".autoapply\workspace"
$LocalBinDir    = Join-Path $env:LOCALAPPDATA "Programs\ApplyLoop"

# ─── Shim-refresh-only fast path ───────────────────────────────────────────
# Used by update.ps1 to regenerate the CLI shim + fallback aliases without
# re-running the full install. We embed the shim-writing logic in a function
# so both the full install path AND this fast path call it identically.
function Write-ApplyloopShim {
    param(
        [Parameter(Mandatory=$true)] [string]$LocalBinDir,
        [Parameter(Mandatory=$true)] [string]$ApplyloopHome,
        [Parameter(Mandatory=$true)] [string]$ExePath,
        [Parameter(Mandatory=$true)] [string]$UpdateScript,
        [Parameter(Mandatory=$true)] [string]$UninstallScript
    )
    New-Item -ItemType Directory -Force -Path $LocalBinDir | Out-Null
    $ShimPath = Join-Path $LocalBinDir "applyloop.cmd"
    # IF /I is the cmd.exe case-insensitive comparator. Without it,
    # `applyloop Update` and `applyloop UPDATE` fall through to the
    # default branch and launch the app instead of pulling latest.
    $shim = @"
@echo off
REM ApplyLoop CLI shim — generated by install.ps1
setlocal
if /I "%~1" == "update" (
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$UpdateScript"
    exit /b %ERRORLEVEL%
)
if /I "%~1" == "uninstall" (
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$UninstallScript" %2 %3
    exit /b %ERRORLEVEL%
)
if /I "%~1" == "version" (
    type "$ApplyloopHome\.applyloop-version"
    exit /b 0
)
if /I "%~1" == "status" (
    powershell.exe -NoProfile -Command "try { Invoke-RestMethod 'http://localhost:18790/api/health' | ConvertTo-Json } catch { Write-Host 'ApplyLoop is not running.'; exit 1 }"
    exit /b %ERRORLEVEL%
)
if /I "%~1" == "stop" (
    powershell.exe -NoProfile -Command "Get-Process -Name 'ApplyLoop' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue; Write-Host 'Stopped.'"
    exit /b 0
)
if /I "%~1" == "logs" (
    powershell.exe -NoProfile -Command "Get-Content '%USERPROFILE%\.autoapply\desktop.log' -Tail 100 -Wait"
    exit /b 0
)
if /I "%~1" == "help"   goto :usage
if /I "%~1" == "-h"     goto :usage
if /I "%~1" == "--help" goto :usage
if /I "%~1" == "start" (
    start "" "$ExePath"
    exit /b 0
)
if "%~1" == "" (
    start "" "$ExePath"
    exit /b 0
)
echo Unknown command: %~1
echo.
:usage
echo Usage: applyloop ^<command^>
echo.
echo   start         Launch the desktop app (default if no command)
echo   stop          Kill any running ApplyLoop.exe
echo   status        Check /api/health
echo   logs          Tail ~/.autoapply/desktop.log
echo   update        Pull latest + rebuild .exe
echo   uninstall     Remove install + .exe + shortcuts + Task Scheduler entry
echo   version       Print current commit
echo   help          Show this message
exit /b 1
"@
    Set-Content -Path $ShimPath -Value $shim -Encoding ASCII
    # Standalone fallback aliases — survive any future dispatcher bug.
    Set-Content -Path (Join-Path $LocalBinDir "applyloop-update.cmd") -Encoding ASCII -Value @"
@echo off
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$UpdateScript" %*
"@
    Set-Content -Path (Join-Path $LocalBinDir "applyloop-uninstall.cmd") -Encoding ASCII -Value @"
@echo off
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$UninstallScript" %*
"@
}

if ($ShimRefreshOnly) {
    Write-Log "Shim-refresh-only mode: regenerating CLI shim + aliases"
    $exeRel = Get-ChildItem -Path (Join-Path $ApplyloopHome "packages\desktop\dist\windows") `
        -Recurse -Filter "ApplyLoop.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $exeRel) { Die "No ApplyLoop.exe found under $ApplyloopHome — run a full install first." }
    Write-ApplyloopShim `
        -LocalBinDir $LocalBinDir `
        -ApplyloopHome $ApplyloopHome `
        -ExePath $exeRel.FullName `
        -UpdateScript (Join-Path $ApplyloopHome "update.ps1") `
        -UninstallScript (Join-Path $ApplyloopHome "uninstall.ps1")
    Write-Log "Shim refreshed → $LocalBinDir\applyloop.cmd (+ applyloop-update.cmd, applyloop-uninstall.cmd)"
    exit 0
}

Write-Log "ApplyLoop install starting"
Write-Log "  AppUrl   = $AppUrl"
Write-Log "  Home     = $ApplyloopHome"
Write-Log "  WS       = $WorkspaceDir"

# ─── Phase A: Activation gate ───────────────────────────────────────────────
$WorkerToken = ""
$ActUserId = ""
$ActEmail = ""
$ActName = ""
$ActProfileJson = ""
$ActTelegramChat = ""

if ($env:APPLYLOOP_SKIP_ACTIVATION) {
    Write-Warn "APPLYLOOP_SKIP_ACTIVATION set — skipping code gate (dev mode)"
} else {
    if (-not $Code) { $Code = $env:APPLYLOOP_CODE }
    if (-not $Code) {
        Write-Host ""
        Write-Host "Before we begin, paste your activation code." -ForegroundColor White
        Write-Host "  (Get this from $AppUrl after admin approval.)" -ForegroundColor Blue
        Write-Host ""
        $Code = Read-Host "  Activation code (AL-XXXX-XXXX)"
        Write-Host ""
    }
    $Code = $Code.ToUpper().Trim()
    if (-not ($Code -match '^AL-[A-Z0-9]{4}-[A-Z0-9]{4}$')) {
        Die "Invalid code format: '$Code'. Expected AL-XXXX-XXXX."
    }

    Write-Log "Validating activation code against $AppUrl..."
    try {
        $hostname = $env:COMPUTERNAME
        $body = @{ code = $Code; install_id = $hostname; app_version = "install.ps1" } | ConvertTo-Json
        $resp = Invoke-RestMethod -Uri "$AppUrl/api/activate" -Method Post `
            -ContentType "application/json" -Body $body -ErrorAction Stop
    } catch {
        $errBody = $_.ErrorDetails.Message
        Die "Activation failed: $errBody`n  Possible causes:`n   1. Code mistyped`n   2. Code revoked or expired`n   3. uses_remaining = 0`n   4. Account not yet approved"
    }

    $data = $resp.data
    if (-not $data.worker_token) { Die "Activation succeeded but no worker_token in response — contact admin" }

    $WorkerToken     = $data.worker_token
    $ActUserId       = $data.user_id
    $ActEmail        = if ($data.email) { $data.email } else { "" }
    $ActName         = if ($data.full_name) { $data.full_name } else { "" }
    $ActTelegramChat = if ($data.telegram_chat_id) { $data.telegram_chat_id } else { "" }
    $ActProfileJson  = $resp | ConvertTo-Json -Depth 20

    $who = if ($ActName) { $ActName } else { $ActEmail }
    Write-Log "Code verified for $who (user $ActUserId)"
}

# ─── Pre-flight: kill any running ApplyLoop process ──────────────────────────
# Without this, a previous install's .exe sits on port 18790 with a file
# lock on its own binary. The new build would write a fresh .exe to disk
# but the OS keeps serving the old one; user thinks "I reinstalled" but
# /api/health still returns the old payload. Reproduced on Shreya's box:
# curl /api/health came back without git_sha (field added in a0dae52)
# even after a fresh install — old .exe was still bound to the port.
try {
    $running = Get-Process -Name "ApplyLoop" -ErrorAction SilentlyContinue
    if ($running) {
        Write-Log "Stopping $($running.Count) running ApplyLoop process(es) so install can replace the .exe"
        $running | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 1
    }
    # Also kill anything still bound to the port — covers an orphaned
    # uvicorn that detached from its parent.
    $portProc = Get-NetTCPConnection -LocalPort 18790 -ErrorAction SilentlyContinue |
        Select-Object -First 1 -ExpandProperty OwningProcess
    if ($portProc) {
        Stop-Process -Id $portProc -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 1
    }
} catch {
    Write-Warn "Could not clean up running processes: $_"
}

# ─── Phase B: Dependency bootstrap (winget) ─────────────────────────────────
function Test-Cmd($name) { return [bool](Get-Command $name -ErrorAction SilentlyContinue) }

function Ensure-Winget {
    if (-not (Test-Cmd "winget")) {
        Die "winget not found. Install 'App Installer' from Microsoft Store first, or use Win10 1809+/Win11."
    }
    Write-Log "winget available: $(winget --version)"
}

function Ensure-WingetPackage($id, $friendly) {
    Write-Log "Ensuring $friendly is installed..."
    $exists = winget list --id $id --exact 2>$null | Select-String $id
    if ($exists) {
        Write-Log "  $friendly already installed"
        return
    }
    # winget can be chatty on stderr (progress bars, license prompts)
    # — same Invoke-Native pattern for the same reason.
    $rc = Invoke-Native "winget install -e --id $id --silent --accept-package-agreements --accept-source-agreements"
    if ($rc -ne 0) {
        Write-Warn "$friendly install via winget reported non-zero exit; verifying..."
    }
}

Ensure-Winget
Ensure-WingetPackage "Python.Python.3.12" "Python 3.12"
Ensure-WingetPackage "OpenJS.NodeJS"      "Node.js 20"
Ensure-WingetPackage "Git.Git"            "Git"

# Refresh PATH so newly-installed tools are visible to this session.
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" + `
            [System.Environment]::GetEnvironmentVariable("PATH", "User")

foreach ($tool in @("python", "node", "npm", "git")) {
    if (-not (Test-Cmd $tool)) {
        Die "$tool still not on PATH after winget install. Open a new PowerShell window and rerun."
    }
}

# Claude Code (via npm — the "claude" Homebrew formula is unrelated and
# wouldn't apply on Windows anyway). All npm calls routed through
# Invoke-Native so deprecation warnings don't blow up the script.
if (Test-Cmd "claude") {
    $claudeVer = & claude --version 2>&1 | Out-String
    if ($claudeVer -match 'anthropic|claude code') {
        Write-Log "claude already installed (Anthropic Claude Code)"
    } else {
        Invoke-Native "npm install -g @anthropic-ai/claude-code" "Replacing non-Anthropic claude with Claude Code" | Out-Null
    }
} else {
    Invoke-Native "npm install -g @anthropic-ai/claude-code" "Installing Claude Code via npm" | Out-Null
}

# OpenClaw (browser automation backbone, also via npm). Always run
# `npm install -g openclaw@latest` — even if a version is already
# present. Previously this short-circuited on any prior install, which
# stranded users on stale openclaw versions whose config schema didn't
# match what install.ps1 was writing.
#
# Routed through Invoke-Native (cmd /c subshell) so npm's deprecation
# warnings (e.g. "npm warn deprecated node-domexception@1.0.0") don't
# escalate to a terminating PowerShell error via the stderr-is-fatal
# trap under $ErrorActionPreference=Stop. That escalation aborted the
# whole install on Shreya's machine even though npm itself succeeded.
$rc = Invoke-Native "npm install -g openclaw@latest --no-fund --no-audit" "Ensuring openclaw is up to date (npm install -g openclaw@latest)"
if ($rc -ne 0) {
    Write-Warn "openclaw npm install returned exit $rc; continuing — local copy may be stale"
}

# Write/repair openclaw config. Previously this only wrote when the file
# was MISSING — so an older install's openclaw.json (missing newer fields
# like browser.profiles.openclaw.cdpPort) would be left in place forever
# and the desktop preflight would forever flag "Config incomplete." Now
# we always merge the required fields into whatever exists, preserving
# the gateway token if one was already generated (re-rolling it would
# break any prior session that's still alive).
$ocDir = Join-Path $env:USERPROFILE ".openclaw"
$ocConfig = Join-Path $ocDir "openclaw.json"
New-Item -ItemType Directory -Force -Path (Join-Path $ocDir "workspace") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $ocDir "agents\main\sessions") | Out-Null

$existingGwToken = $null
if (Test-Path $ocConfig) {
    try {
        $existing = Get-Content $ocConfig -Raw | ConvertFrom-Json
        if ($existing.gateway -and $existing.gateway.auth -and $existing.gateway.auth.token) {
            $existingGwToken = $existing.gateway.auth.token
            Write-Log "Reusing existing openclaw gateway token"
        }
    } catch {
        Write-Warn "Existing openclaw.json was unparseable — regenerating from scratch"
    }
}
$gwToken = if ($existingGwToken) { $existingGwToken } else { -join ((1..24) | ForEach-Object { '{0:x2}' -f (Get-Random -Min 0 -Max 256) }) }
$nowIso = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
# Probe the actually-installed openclaw version. We used to hardcode
# "2026.5.9" — openclaw refuses to load a config that claims a newer
# version than itself ("Config was last written by a newer OpenClaw"),
# so any user whose npm openclaw lagged behind that string was bricked.
# Now we ask openclaw what it is and write that. Fallback "0.0.0" if
# the probe fails — openclaw treats that as legacy/unknown which is
# safer than a future version.
$ocVer = "0.0.0"
try {
    $verRaw = (& openclaw --version 2>$null | Select-Object -First 1).ToString().Trim()
    if ($verRaw -match '(\d+\.\d+\.\d+)') { $ocVer = $matches[1] }
} catch {}
Write-Log "OpenClaw version probed as: $ocVer"
$ocJson = @"
{
  "meta": { "lastTouchedVersion": "$ocVer", "lastTouchedAt": "$nowIso" },
  "wizard": { "lastRunAt": "$nowIso", "lastRunMode": "local", "lastRunCommand": "applyloop-install" },
  "browser": {
    "defaultProfile": "openclaw",
    "profiles": { "openclaw": { "cdpPort": 18800, "color": "#0066CC" } }
  },
  "gateway": {
    "port": 18789, "mode": "local", "bind": "loopback",
    "auth": { "mode": "token", "token": "$gwToken" }
  },
  "commands": { "native": "auto", "nativeSkills": "auto" }
}
"@
Write-Log "Writing $ocConfig (force-rewrite to include required fields)"
Write-Utf8NoBom -Path $ocConfig -Content $ocJson

# Start the gateway and verify it actually bound. Routed through
# Invoke-Native (cmd /c) so any startup chatter on stderr — npm/node
# warnings, OpenClaw's own info messages — doesn't escalate to a
# terminating PowerShell error under $ErrorActionPreference=Stop.
Invoke-Native "openclaw gateway start" "Starting openclaw gateway..." | Out-Null
Start-Sleep -Seconds 2
# Probe — the gateway listens on the port we just wrote.
$gwUp = $false
try {
    $probe = Test-NetConnection -ComputerName 127.0.0.1 -Port 18789 -InformationLevel Quiet -WarningAction SilentlyContinue
    if ($probe) { $gwUp = $true }
} catch {}
if ($gwUp) {
    Write-Log "OpenClaw gateway is listening on 127.0.0.1:18789"
} else {
    Write-Warn "OpenClaw gateway didn't come up via 'openclaw gateway start'. Retrying with explicit config path..."
    Start-Process -FilePath "openclaw" -ArgumentList @("gateway", "start", "--config", $ocConfig) -NoNewWindow -WindowStyle Hidden | Out-Null
    Start-Sleep -Seconds 3
    try {
        $probe2 = Test-NetConnection -ComputerName 127.0.0.1 -Port 18789 -InformationLevel Quiet -WarningAction SilentlyContinue
        if ($probe2) { Write-Log "OpenClaw gateway is now up after retry" }
        else { Write-Warn "OpenClaw gateway still not responding. The desktop will retry on demand; if it persists, click 'Install' on the OpenClaw gateway row in the setup checklist." }
    } catch {
        Write-Warn "OpenClaw gateway probe failed: $_"
    }
}

# ─── Phase C: Clone / update repo ───────────────────────────────────────────
$parentDir = Split-Path $ApplyloopHome -Parent
New-Item -ItemType Directory -Force -Path $parentDir | Out-Null

if (Test-Path (Join-Path $ApplyloopHome ".git")) {
    Write-Log "Existing install at $ApplyloopHome — fetching $Branch"
    git -C $ApplyloopHome fetch origin $Branch
    git -C $ApplyloopHome reset --hard "origin/$Branch"
} else {
    Write-Log "Cloning $RepoUrl (branch=$Branch) → $ApplyloopHome"
    git clone --depth 1 --branch $Branch $RepoUrl $ApplyloopHome
}

# ─── Phase D: Python venv + deps ────────────────────────────────────────────
$VenvDir = Join-Path $ApplyloopHome "venv"
$VenvPy  = Join-Path $VenvDir "Scripts\python.exe"
$VenvPip = Join-Path $VenvDir "Scripts\pip.exe"

if (-not (Test-Path $VenvPy)) {
    Write-Log "Creating venv at $VenvDir"
    python -m venv $VenvDir
}
if (-not (Test-Path $VenvPy)) { Die "venv creation failed — $VenvPy missing" }

Write-Log "Upgrading pip"
& $VenvPip install --quiet --upgrade pip

Write-Log "Installing desktop + worker python deps"
& $VenvPip install `
    -r (Join-Path $ApplyloopHome "packages\desktop\requirements.txt") `
    -r (Join-Path $ApplyloopHome "packages\worker\requirements.txt")

# Install pyinstaller separately so build.py --win works for local rebuilds
& $VenvPip install --quiet "pyinstaller>=6.0"

# ─── Phase E: UI build ──────────────────────────────────────────────────────
# NPM cache isolation — same reason install.sh isolates: the global cache
# can collide with whatever node version + npm version the user has from
# previous installs (e.g. nvm-windows path drift), and on the Vercel CI
# runner an npm install with a polluted global cache produced sporadic
# EACCES failures. Keep our cache local and predictable.
$env:NPM_CONFIG_CACHE = Join-Path $ApplyloopHome ".npm-cache"
New-Item -ItemType Directory -Force -Path $env:NPM_CONFIG_CACHE | Out-Null

Write-Log "Building static Next.js UI"
$uiDir = Join-Path $ApplyloopHome "packages\desktop\ui"
Push-Location $uiDir
try {
    npm install --cache $env:NPM_CONFIG_CACHE --no-fund --no-audit
    npm run build
} finally {
    Pop-Location
}

# ─── Phase F: Cloud config + profile.json ───────────────────────────────────
$TelegramBotToken = ""
$SupabaseUrl = ""
$SupabaseAnonKey = ""
$CliConfigJson = ""
$AgentmailKey = ""
$FinetuneKey = ""
$GmailEmail = ""
$GmailAppPw = ""

if ($WorkerToken) {
    Write-Log "Fetching cli-config..."
    try {
        $cfg = Invoke-RestMethod -Uri "$AppUrl/api/settings/cli-config" `
            -Headers @{ "X-Worker-Token" = $WorkerToken } -ErrorAction Stop
        $CliConfigJson = $cfg | ConvertTo-Json -Depth 20
        $d = $cfg.data
        if ($d.telegram_bot_token) { $TelegramBotToken = $d.telegram_bot_token }
        if ($d.supabase_url)       { $SupabaseUrl       = $d.supabase_url }
        if ($d.supabase_anon_key)  { $SupabaseAnonKey   = $d.supabase_anon_key }
        if (-not $ActTelegramChat -and $d.telegram_chat_id) { $ActTelegramChat = $d.telegram_chat_id }
    } catch {
        Write-Warn "cli-config fetch failed: $($_.Exception.Message) — Telegram + Supabase config will be empty"
    }

    Write-Log "Fetching saved integrations..."
    try {
        $intResp = Invoke-RestMethod -Uri "$AppUrl/api/settings/integrations?raw=1" `
            -Headers @{ "X-Worker-Token" = $WorkerToken } -ErrorAction Stop
        $i = $intResp.data.integrations
        if ($i.telegram_bot_token)     { $TelegramBotToken = $i.telegram_bot_token }
        if ($i.telegram_chat_id -and -not $ActTelegramChat) { $ActTelegramChat = $i.telegram_chat_id }
        if ($i.gmail_email)            { $GmailEmail = $i.gmail_email }
        if ($i.gmail_app_password)     { $GmailAppPw = $i.gmail_app_password }
        if ($i.agentmail_api_key)      { $AgentmailKey = $i.agentmail_api_key }
        if ($i.finetune_resume_api_key){ $FinetuneKey = $i.finetune_resume_api_key }
        $filled = @($TelegramBotToken, $ActTelegramChat, $GmailEmail, $GmailAppPw, $AgentmailKey, $FinetuneKey) | Where-Object { $_ }
        if ($filled.Count -gt 0) { Write-Log "  Loaded $($filled.Count) integration(s) from cloud" }
    } catch {
        Write-Log "  No saved integrations (or endpoint unavailable)"
    }
}

# Transform activate + cli-config into the nested profile.json shape via
# Python (mirrors install.sh exactly so behavior is identical).
if ($ActProfileJson) {
    Write-Log "Writing profile.json"
    $actTmp = Join-Path $env:TEMP "applyloop-activate.json"
    $cfgTmp = Join-Path $env:TEMP "applyloop-cliconfig.json"
    Write-Utf8NoBom -Path $actTmp -Content $ActProfileJson
    Write-Utf8NoBom -Path $cfgTmp -Content $CliConfigJson
    $env:APPLYLOOP_HOME_FOR_PY = $ApplyloopHome
    $env:ACTIVATE_PATH = $actTmp
    $env:CLI_CONFIG_PATH = $cfgTmp
    $pyTransform = @'
import json, os

def load(path):
    try:
        with open(path) as f:
            return json.loads(f.read()).get("data", {}) or {}
    except Exception:
        return {}

act = load(os.environ["ACTIVATE_PATH"])
cfg = load(os.environ.get("CLI_CONFIG_PATH", ""))
cfg_profile = cfg.get("profile") or {}
act_profile = act.get("profile") or {}
cfg_prefs = cfg.get("preferences") or {}
act_prefs = act.get("preferences") or {}

def pick(key, default=None):
    v = cfg_profile.get(key)
    if v not in (None, "", [], {}):
        return v
    return act_profile.get(key) if act_profile.get(key) not in (None, "") else default

user_id = act.get("user_id") or (cfg.get("user", {}) or {}).get("id") or ""
email = act.get("email") or (cfg.get("user", {}) or {}).get("email") or ""
full_name = act.get("full_name") or (cfg.get("user", {}) or {}).get("full_name") or ""
tier = act.get("tier") or cfg.get("tier") or ""

profile = {
  "user": {"id": user_id, "email": email, "full_name": full_name, "tier": tier},
  "personal": {
    "first_name": pick("first_name", "") or "",
    "last_name": pick("last_name", "") or "",
    "email": email,
    "phone": pick("phone", "") or "",
    "linkedin_url": pick("linkedin_url", "") or "",
    "github_url": pick("github_url", "") or "",
    "portfolio_url": pick("portfolio_url", "") or "",
  },
  "work": {
    "current_company": pick("current_company", "") or "",
    "current_title": pick("current_title", "") or "",
    "years_experience": pick("years_experience", "") or "",
  },
  "legal": {
    "work_authorization": pick("work_authorization", "") or "",
    "requires_sponsorship": pick("requires_sponsorship", False) or False,
  },
  "eeo": {
    "gender": pick("gender", "") or "",
    "race_ethnicity": pick("race_ethnicity", "") or "",
    "veteran_status": pick("veteran_status", "") or "",
    "disability_status": pick("disability_status", "") or "",
  },
  "experience": pick("work_experience", []) or [],
  "education": pick("education", "") or "",
  "education_summary": {
    "education_level": pick("education_level", "") or "",
    "school_name": pick("school_name", "") or "",
    "degree": pick("degree", "") or "",
    "graduation_year": pick("graduation_year", "") or "",
  },
  "skills": pick("skills", []) or [],
  "standard_answers": pick("answer_key_json", {}) or {},
  "cover_letter_template": pick("cover_letter_template", "") or "",
  "preferences": cfg_prefs or act_prefs or {},
  "resumes": [act.get("default_resume")] if act.get("default_resume") else [],
}

home = os.environ["APPLYLOOP_HOME_FOR_PY"]
os.makedirs(home, exist_ok=True)
with open(os.path.join(home, "profile.json"), "w") as f:
    json.dump(profile, f, indent=2)
print(f"  wrote {len(profile['experience'])} experience, {len(profile['skills'])} skills")
'@
    $pyScript = Join-Path $env:TEMP "applyloop-profile-transform.py"
    Write-Utf8NoBom -Path $pyScript -Content $pyTransform
    & $VenvPy $pyScript
    Remove-Item $actTmp, $cfgTmp, $pyScript -ErrorAction SilentlyContinue
}

# Persist worker token to disk where desktop wizard expects it
$TokenFile = Join-Path $WorkspaceDir ".api-token"
New-Item -ItemType Directory -Force -Path $WorkspaceDir | Out-Null
if ($WorkerToken) {
    Write-Utf8NoBom -Path $TokenFile -Content $WorkerToken
    # Owner-only ACL (Windows equivalent of chmod 600). Best-effort.
    try {
        icacls $TokenFile /inheritance:r /grant:r "$($env:USERNAME):F" 2>&1 | Out-Null
    } catch {}
    Write-Log "Worker token saved to $TokenFile"
}

# ─── Phase G: Write .env ────────────────────────────────────────────────────
$EnvFile = Join-Path $ApplyloopHome ".env"

# Idempotency: if a previous install wrote .env, parse it and preserve
# values the user (or a prior cloud sync) populated for fields the
# cloud might NOT return this run. install.sh's reuse_or_prompt logic
# does the same on Mac. Without this, a re-run wipes Telegram /
# AgentMail / Finetune / Gmail values back to empty whenever those
# integrations weren't saved on the cloud yet.
$existingEnv = @{}
if (Test-Path $EnvFile) {
    Get-Content $EnvFile | ForEach-Object {
        if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$') {
            $existingEnv[$matches[1]] = $matches[2]
        }
    }
    Write-Log "Found existing .env — preserving local overrides"
}

# For each field that can be populated locally but not always returned
# by the cloud, prefer the existing value when the cloud one is empty.
function _preserve($name, $newValue) {
    if (-not $newValue -and $existingEnv.ContainsKey($name)) {
        return $existingEnv[$name]
    }
    return $newValue
}
$TelegramBotToken = _preserve "TELEGRAM_BOT_TOKEN" $TelegramBotToken
$ActTelegramChat  = _preserve "TELEGRAM_CHAT_ID"   $ActTelegramChat
$AgentmailKey     = _preserve "AGENTMAIL_API_KEY"  $AgentmailKey
$FinetuneKey      = _preserve "FINETUNE_RESUME_API_KEY" $FinetuneKey
$GmailEmail       = _preserve "GMAIL_EMAIL"        $GmailEmail
$GmailAppPw       = _preserve "GMAIL_APP_PASSWORD" $GmailAppPw

# ENCRYPTION_KEY MUST be preserved across reinstalls — anything encrypted
# under the old key becomes unreadable if we generate a fresh one. If
# .env had one, reuse it; only generate a new key on a true first install.
if ($existingEnv.ContainsKey("ENCRYPTION_KEY") -and $existingEnv["ENCRYPTION_KEY"]) {
    $EncryptionKey = $existingEnv["ENCRYPTION_KEY"]
} else {
    $EncryptionKey = -join ((1..32) | ForEach-Object { '{0:x2}' -f (Get-Random -Min 0 -Max 256) })
}
$WorkerId = "worker-$($env:COMPUTERNAME.ToLower())-$(Get-Random)"

Write-Log "Writing $EnvFile"
$resumeDir = Join-Path $WorkspaceDir "resumes"
$screenshotDir = Join-Path $WorkspaceDir "screenshots"
$dbPath = Join-Path $WorkspaceDir "applications.db"
$envContent = @"
# ApplyLoop runtime config — generated by install.ps1 on $((Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ"))
# Read by the desktop launcher and worker subprocess on Windows.
# Edit carefully. To regenerate: rerun install.ps1.

# ── Auth (REQUIRED) ────────────────────────────────────────────────
WORKER_TOKEN=$WorkerToken

# Tenant identity — worker.py main() reads this and loads TenantConfig.
APPLYLOOP_USER_ID=$ActUserId

# ── App ────────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_URL=$AppUrl
APPLYLOOP_HOME=$ApplyloopHome
ENCRYPTION_KEY=$EncryptionKey

# ── Supabase (shared admin instance) ──────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=$SupabaseUrl
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SupabaseAnonKey
SUPABASE_URL=$SupabaseUrl
SUPABASE_SERVICE_KEY=$SupabaseAnonKey

# ── Worker tuning ─────────────────────────────────────────────────
WORKER_ID=$WorkerId
POLL_INTERVAL=10
APPLY_COOLDOWN=30
APPLYLOOP_WORKSPACE=$WorkspaceDir
APPLYLOOP_DB=$dbPath
RESUME_DIR=$resumeDir
SCREENSHOT_DIR=$screenshotDir

# ── Telegram ──────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN=$TelegramBotToken
TELEGRAM_CHAT_ID=$ActTelegramChat

# ── Optional integrations ─────────────────────────────────────────
AGENTMAIL_API_KEY=$AgentmailKey
FINETUNE_RESUME_API_KEY=$FinetuneKey
GMAIL_EMAIL=$GmailEmail
GMAIL_APP_PASSWORD=$GmailAppPw
"@
Write-Utf8NoBom -Path $EnvFile -Content $envContent
try {
    icacls $EnvFile /inheritance:r /grant:r "$($env:USERNAME):F" 2>&1 | Out-Null
} catch {}

# Himalaya IMAP config from Gmail creds (mirrors install.sh:1112-1135).
# himalaya_reader.py also calls ensure_configured() at apply time so
# users who update creds via Settings don't need to reinstall, but we
# write it here so first-launch Gmail verification works without a
# round-trip. Without this on Windows, the worker tries to fetch
# verification codes and fails silently.
if ($GmailEmail -and $GmailAppPw) {
    # Himalaya looks for config under %APPDATA%\himalaya by default on
    # Windows (via the dirs crate's Windows AppData mapping).
    $himCfgDir = Join-Path $env:APPDATA "himalaya"
    New-Item -ItemType Directory -Force -Path $himCfgDir | Out-Null
    $himCfg = Join-Path $himCfgDir "config.toml"
    $himContent = @"
[accounts.gmail]
email = "$GmailEmail"
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "$GmailEmail"
backend.auth.type = "password"
backend.auth.raw = "$GmailAppPw"
folder.aliases.inbox = "INBOX"
folder.aliases.sent = "[Gmail]/Sent Mail"
folder.aliases.drafts = "[Gmail]/Drafts"
folder.aliases.trash = "[Gmail]/Trash"
"@
    Write-Utf8NoBom -Path $himCfg -Content $himContent
    try {
        icacls $himCfg /inheritance:r /grant:r "$($env:USERNAME):F" 2>&1 | Out-Null
    } catch {}
    Write-Log "Himalaya config written for $GmailEmail → $himCfg"
}

# CLIENT.md (preserved across updates — never overwrite)
$ClientMd = Join-Path $ApplyloopHome "CLIENT.md"
if (-not (Test-Path $ClientMd)) {
    $clientContent = @"
# CLIENT.md — Your personal overrides
#
# This file is NEVER overwritten by 'applyloop update'.
# Add anything here that should take precedence over the global rules.
#
# Examples:
#   - Companies to exclude (beyond what your online preferences block):
#       Never apply to: Acme Corp, Example Inc
#
#   - Title preferences / blacklist:
#       Skip any role with "Manager" in the title — I only want IC roles.
#
#   - Location notes:
#       Remote-only. Reject anything requiring relocation to TX or FL.
#
#   - Cover letter tone / style notes:
#       Keep the cover letter to 3 short paragraphs. No buzzwords.
#
#   - Any one-off instruction that doesn't belong in the shared profile:
#       If a form asks for expected salary, enter 120000.
#
# Lines starting with # are comments and are ignored by Claude.
# Delete the example lines and replace with your own instructions.
"@
    Write-Utf8NoBom -Path $ClientMd -Content $clientContent
    Write-Log "Created $ClientMd"
}

# Worker runtime dirs
New-Item -ItemType Directory -Force -Path $resumeDir, $screenshotDir | Out-Null

# Cache resume PDF
if ($WorkerToken) {
    Write-Log "Downloading resume PDF for local Claude parsing"
    $resumeTarget = Join-Path $resumeDir "default.pdf"
    try {
        Invoke-WebRequest -Uri "$AppUrl/api/onboarding/resume/download" `
            -Headers @{ "X-Worker-Token" = $WorkerToken } `
            -OutFile $resumeTarget -ErrorAction Stop
        $head = [System.IO.File]::ReadAllBytes($resumeTarget)[0..3] -join ","
        if ($head -eq "37,80,68,70") {  # %PDF
            $size = (Get-Item $resumeTarget).Length
            Write-Log "  Resume cached — $size bytes"
        } else {
            Write-Warn "Downloaded resume isn't a valid PDF, deleting"
            Remove-Item $resumeTarget -ErrorAction SilentlyContinue
        }
    } catch {
        Write-Warn "Resume download failed — Claude will ask interactively on first launch"
    }
}

# ─── Phase H: AGENTS.md + .claude/settings.json ─────────────────────────────
$AgentsFile = Join-Path $ApplyloopHome "AGENTS.md"
Write-Log "Writing $AgentsFile"
$hasTelegram = if ($ActTelegramChat -and $TelegramBotToken) { "yes ($ActTelegramChat)" } else { "no" }
$hasAgentmail = if ($AgentmailKey) { "yes" } else { "no" }
$hasFinetune  = if ($FinetuneKey) { "yes" } else { "no" }
$hasGmail     = if ($GmailEmail) { "yes ($GmailEmail)" } else { "no" }
$pyVenvPath   = $VenvPy

$agentsContent = @"
# ApplyLoop — Agent Context (Windows)

You are the ApplyLoop job application agent. ApplyLoop is an automated
job application engine that runs locally on this Windows machine.

## System info

- **Install directory**: ``$ApplyloopHome``
- **Python venv**: ``$pyVenvPath``
- **Profile**: ``$ApplyloopHome\profile.json`` — read this FIRST (the user you're applying for)
- **Playbook**: ``$ApplyloopHome\packages\worker\SOUL.md`` — the full scout→apply rules
- **Config env**: ``$ApplyloopHome\.env`` — sourced by launcher
- **Desktop log**: ``$env:USERPROFILE\.autoapply\desktop.log``
- **Workspace**: ``$WorkspaceDir``
- **User**: ${ActName}
- **User email**: ${ActEmail}

## Your role — YOU are the single orchestrator

You own the complete pipeline end-to-end via MCP tool calls:

  **SCOUT → FILTER → ENQUEUE → APPLY → CONFIRM → SCREENSHOT → LOG → TELEGRAM**

1. **Read ``profile.json`` first.** Every field (experience, education, skills, answer_key_json, preferences) is the source of truth for form-filling.
2. **Read ``SOUL.md``** for the full playbook: scanning strategy, filters, form-filling rules, rate limits, critical do-nots.
3. **Greet the user by name** (``${ActName}``) in ONE line, then **IMMEDIATELY start the pipeline**. Do NOT wait for a "start" command.
4. On "status": show profile summary + last scout/apply stats + configured services (below).
5. On "apply to [URL]": apply directly to that URL using browser MCP tools.
6. On "stop": stop the loop, send a session summary via Telegram.

## Watchdog nudges

A background watchdog will inject status messages into this terminal every ~30 minutes when you are idle. Nudge format:

  ``[applyloop-watchdog HH:MM] queue=N pending, applied_today=X/Y, scout_last=Zmin ago, idle=Wmin. <recommended action>.``

**Act on nudges immediately.** The nudge tells you exactly what to do next — no need to re-derive state.

## Pipeline steps (MCP tools)

- **Scout**: ``scout_list_sources`` → ``scout_run_source(name)`` for each source
- **Filter**: ``tenant_load`` → apply role/location/blocklist/dedup filters
- **Enqueue**: ``queue_update_status`` for each filtered job → status=pending
- **Apply**: ``queue_claim_next`` → ``knowledge_get_ats_playbook`` → browser_navigate/snapshot/fill/click
- **Confirm**: snapshot again → look for "thank you" / "application received" (positive only)
- **Screenshot**: ``browser_screenshot`` → local PNG saved to ``$WorkspaceDir\screenshots\``
- **Log**: ``queue_log_application(job_id, status=submitted, screenshot_path=local_path)``
- **Telegram**: ``notify_telegram(kind=application_result, screenshot_path=local_path)`` → sendPhoto binary

## Daily limit

Check ``queue_get_pipeline`` for ``applied_today`` vs ``daily_limit``. When limit is reached:
- Stop applying
- Send a session summary via ``notify_telegram``
- Wait for the next session

## Configured services

- **Telegram notifications**: $hasTelegram
- **AgentMail** (disposable inboxes): $hasAgentmail
- **Finetune Resume** (per-job tailored PDFs): $hasFinetune
- **Gmail + Himalaya** (email verification codes): $hasGmail

## Critical rules

- NEVER skip required form fields.
- NEVER apply to a company more than 5 times per 15 days.
- ALWAYS take a screenshot after submission and log it + Telegram notify.
- ALWAYS use ``queue_claim_next`` (row-lock) — never pull from queue without claiming.
- Call ``browser_dismiss_stray_tabs`` between every apply step.
- If OpenClaw gateway crashes: run ``openclaw gateway restart`` and continue.
- **NEVER spawn a separate Claude process or brain loop** — you are the only brain.
- If you hit a rate limit or auth error: surface it to the user in chat + Telegram, wait for fix.

## Platform notes (Windows-specific)

- Paths use ``\`` separators. Code uses pathlib so most call sites are invisible.
- Local SQLite at ``$dbPath`` is the source of truth.
- Use ``tempfile.gettempdir()`` for temp paths (resolves to %TEMP%).
- ``keep_awake.start()`` is no-op on non-Windows — on Windows it blocks sleep via SetThreadExecutionState during applies.

## Handy commands the user might ask for

- ``applyloop start`` / ``applyloop stop`` / ``applyloop status`` / ``applyloop logs``
- ``applyloop update`` — git pull + rebuild (logs to %USERPROFILE%\.autoapply\update.log)
- ``applyloop uninstall`` — remove install + .exe + Task Scheduler entry; preserves workspace
- ``applyloop version`` — show current commit
"@
Write-Utf8NoBom -Path $AgentsFile -Content $agentsContent

# .claude/settings.json — register MCP server
$ClaudeDir = Join-Path $ApplyloopHome ".claude"
New-Item -ItemType Directory -Force -Path $ClaudeDir | Out-Null
$ClaudeSettings = Join-Path $ClaudeDir "settings.json"
$workerCwd = Join-Path $ApplyloopHome "packages\worker"
# Escape backslashes for JSON
$pyEscaped = $VenvPy -replace '\\', '\\'
$cwdEscaped = $workerCwd -replace '\\', '\\'
$homeEscaped = $ApplyloopHome -replace '\\', '\\'

$claudeJson = @"
{
  "mcpServers": {
    "applyloop": {
      "command": "$pyEscaped",
      "args": ["-m", "brain.mcp_server"],
      "env": {
        "PYTHONPATH": "$cwdEscaped",
        "APPLYLOOP_USER_ID": "$ActUserId",
        "APPLYLOOP_HOME": "$homeEscaped"
      },
      "cwd": "$cwdEscaped"
    }
  }
}
"@
Write-Utf8NoBom -Path $ClaudeSettings -Content $claudeJson
Write-Log "Wrote $ClaudeSettings"

# ─── Phase I: Build the .exe ───────────────────────────────────────────────
Write-Log "Building Windows .exe via packages\desktop\build.py --win"
$buildScript = Join-Path $ApplyloopHome "packages\desktop\build.py"
Push-Location (Split-Path $buildScript)
try {
    & $VenvPy $buildScript --win --skip-ui
} finally {
    Pop-Location
}

# ─── Phase J: CLI shim + PATH ──────────────────────────────────────────────
New-Item -ItemType Directory -Force -Path $LocalBinDir | Out-Null
$ShimPath = Join-Path $LocalBinDir "applyloop.cmd"

# Find the built ApplyLoop.exe
$ExePath = Get-ChildItem -Path (Join-Path $ApplyloopHome "packages\desktop\dist\windows") `
    -Recurse -Filter "ApplyLoop.exe" -ErrorAction SilentlyContinue | Select-Object -First 1

# Write the update script that `applyloop update` and Task Scheduler will
# call. The .exe doesn't parse CLI args (it's a single-purpose desktop
# launcher), so update can't go through it — it has to be a separate
# PowerShell entry point that does the git/pip/npm work directly.
#
# Mirrors the Mac update path's fail-fast model (Mac uses `set -euo pipefail`).
# Earlier version used $ErrorActionPreference = 'Continue' which silently
# swallowed git/pip/npm failures and still bumped .applyloop-version to
# a broken commit — caught by the parity audit, fixed here:
#   - $ErrorActionPreference = 'Stop'  (exit on any failure)
#   - Wrap each phase in try/catch so we know which step failed
#   - Capture the pre-update commit FIRST; only stamp .applyloop-version
#     after every step succeeds (so a partial failure leaves the version
#     pointing at the last-known-good commit, not a broken half-update)
#   - Tee everything (stdout + stderr) to %USERPROFILE%\.autoapply\update.log
#     so the daily 3 AM Task Scheduler run leaves a paper trail (was
#     invisible — caught by the audit)
$UpdateScript = Join-Path $ApplyloopHome "update.ps1"
$UpdateScriptContent = @"
# ApplyLoop update script — generated by install.ps1.
# Re-runs git fetch + reset, reinstalls Python deps if requirements changed,
# rebuilds the UI bundle, rebuilds the .exe. Idempotent. Fail-fast: any
# step erroring stops the script and leaves the install at the previous
# known-good commit.
[CmdletBinding()] param()
`$ErrorActionPreference = 'Stop'
`$AppHome = '$ApplyloopHome'
`$Venv = Join-Path `$AppHome 'venv\Scripts'
`$Py   = Join-Path `$Venv 'python.exe'
`$Pip  = Join-Path `$Venv 'pip.exe'
`$LogDir  = Join-Path `$env:USERPROFILE '.autoapply'
`$LogFile = Join-Path `$LogDir 'update.log'
New-Item -ItemType Directory -Force -Path `$LogDir | Out-Null
function Log(`$msg) {
    `$line = "[`$(Get-Date -Format 'u')] `$msg"
    Write-Host `$line
    Add-Content -Path `$LogFile -Value `$line
}
# Concurrency lock — prevents the daily 3 AM Task Scheduler run from
# colliding with a manual `applyloop update` invoked at the same moment.
# Both would otherwise race on .git/index.lock and the venv. The lock
# file holds the holder's PID; if a stale lock from a crashed prior
# update is present (PID dead), we steal it.
`$LockFile = Join-Path `$LogDir '.update.lock'
if (Test-Path `$LockFile) {
    `$stalePid = (Get-Content `$LockFile -ErrorAction SilentlyContinue | Select-Object -First 1)
    `$alive = `$false
    if (`$stalePid) {
        try { `$alive = [bool](Get-Process -Id `$stalePid -ErrorAction Stop) } catch { `$alive = `$false }
    }
    if (`$alive) {
        Log "Another applyloop update is already running (pid `$stalePid). Aborting."
        exit 1
    }
    Log "Stale lock from dead pid `$stalePid — clearing"
    Remove-Item `$LockFile -Force -ErrorAction SilentlyContinue
}
`$PID | Out-File -Encoding ASCII `$LockFile

try {
    `$prevCommit = git -C `$AppHome rev-parse HEAD
    Log "applyloop-update starting (was at `$prevCommit)"
    Log "Pulling latest from origin/main..."
    git -C `$AppHome fetch origin main 2>&1 | Tee-Object -FilePath `$LogFile -Append
    git -C `$AppHome reset --hard origin/main 2>&1 | Tee-Object -FilePath `$LogFile -Append
    Log "Reinstalling Python deps (no-op if up to date)..."
    & `$Pip install --quiet -r (Join-Path `$AppHome 'packages\desktop\requirements.txt') 2>&1 | Tee-Object -FilePath `$LogFile -Append
    & `$Pip install --quiet -r (Join-Path `$AppHome 'packages\worker\requirements.txt') 2>&1 | Tee-Object -FilePath `$LogFile -Append
    Log "Rebuilding UI..."
    Push-Location (Join-Path `$AppHome 'packages\desktop\ui')
    try {
        npm install --silent --no-fund --no-audit 2>&1 | Tee-Object -FilePath `$LogFile -Append
        npm run build 2>&1 | Tee-Object -FilePath `$LogFile -Append
    } finally { Pop-Location }
    Log "Rebuilding Windows .exe..."
    & `$Py (Join-Path `$AppHome 'packages\desktop\build.py') --win --skip-ui 2>&1 | Tee-Object -FilePath `$LogFile -Append

    # Stop the running app (parity with Mac's cmd_stop). Forces the
    # user to relaunch and pick up the new .exe; otherwise a long-lived
    # session keeps holding the stale binary in memory.
    Log "Stopping running ApplyLoop.exe (if any) so the next launch uses the new build..."
    Get-Process -Name "ApplyLoop" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue

    # Refresh Start Menu + Desktop .lnk shortcuts. The icon comes from
    # the .exe (embedded via PyInstaller --icon), so a rebuild changes
    # the icon bytes but Explorer caches .lnk thumbnails — Windows can
    # keep showing the OLD icon until the .lnk is re-saved. Re-writing
    # the shortcuts forces a cache invalidation.
    try {
        `$exeRel = Get-ChildItem -Path (Join-Path `$AppHome 'packages\desktop\dist\windows') -Recurse -Filter "ApplyLoop.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
        if (`$exeRel) {
            `$icon = Join-Path `$AppHome 'packages\desktop\icon.ico'
            if (-not (Test-Path `$icon)) { `$icon = `$exeRel.FullName }
            `$startLnk   = Join-Path `$env:APPDATA 'Microsoft\Windows\Start Menu\Programs\ApplyLoop.lnk'
            `$desktopLnk = Join-Path ([System.Environment]::GetFolderPath('Desktop')) 'ApplyLoop.lnk'
            `$wsh = New-Object -ComObject WScript.Shell
            foreach (`$lnk in @(`$startLnk, `$desktopLnk)) {
                `$sc = `$wsh.CreateShortcut(`$lnk)
                `$sc.TargetPath       = `$exeRel.FullName
                `$sc.WorkingDirectory = Split-Path `$exeRel.FullName -Parent
                `$sc.IconLocation     = `$icon
                `$sc.Description      = 'ApplyLoop -- automated job-application desktop app'
                `$sc.Save()
            }
            Log "Refreshed Start Menu + Desktop shortcuts (icon source: `$icon)"
        }
    } catch {
        Log "Shortcut refresh failed: `$(`$_.Exception.Message)"
    }

    # Self-heal the CLI shim. The dispatch logic (case-insensitive
    # verb matching, fallback aliases, etc.) lives in install.ps1.
    # Re-invoking it in shim-refresh-only mode regenerates the shim
    # from the latest source so any client running an older broken
    # shim recovers on the next update. Concrete repro: client typed
    # `applyloop update` on a shim whose IF was case-sensitive ->
    # mismatched capitalization or muscle-typed Title-case fell
    # through to the default and launched the app instead.
    try {
        `$installPs1 = Join-Path `$AppHome 'install.ps1'
        if (Test-Path `$installPs1) {
            Log "Refreshing CLI shim from latest install.ps1..."
            & powershell.exe -NoProfile -ExecutionPolicy Bypass -File `$installPs1 -ShimRefreshOnly 2>&1 | Tee-Object -FilePath `$LogFile -Append
            Log "Shim refresh: exit `$LASTEXITCODE"
        }
    } catch {
        Log "Shim refresh failed: `$(`$_.Exception.Message)"
    }

    # ONLY stamp the version after every step above has succeeded.
    # If any threw, we exit via the catch with the version untouched.
    git -C `$AppHome rev-parse HEAD | Out-File -Encoding UTF8 (Join-Path `$AppHome '.applyloop-version')
    Log "Done. Update succeeded."
} catch {
    Log "FAILED at step: `$(`$_.Exception.Message)"
    Log "Install left at previous version `$prevCommit (.applyloop-version unchanged)"
    exit 1
} finally {
    Remove-Item `$LockFile -Force -ErrorAction SilentlyContinue
}
"@
Write-Utf8NoBom -Path $UpdateScript -Content $UpdateScriptContent
Write-Log "Update script → $UpdateScript (fail-fast, logged to ~/.autoapply/update.log)"

# Uninstaller — mirrors Mac's cmd_uninstall in packages/desktop/scripts/applyloop.
# Stops Task Scheduler entry, removes installed code/binaries/shim, removes API
# token from workspace. PRESERVES the workspace (~/.autoapply) so user keeps
# their applications.db, resumes, screenshots — re-installing later picks
# right back up where they left off.
$UninstallScript = Join-Path $ApplyloopHome "uninstall.ps1"
$UninstallScriptContent = @"
# ApplyLoop uninstaller — generated by install.ps1.
# Removes: Task Scheduler entry, install dir, .exe + shim, API token.
# Preserves: ~/.autoapply workspace (db, resumes, screenshots) so a
# future reinstall keeps your job history. Run with `applyloop uninstall`.
[CmdletBinding()] param([switch]`$Force)
if (-not `$Force) {
    Write-Host "ApplyLoop uninstall — this removes:"
    Write-Host "  - Daily auto-update task (Task Scheduler)"
    Write-Host "  - $ApplyloopHome (source, venv, .env, profile.json)"
    Write-Host "  - $LocalBinDir (the .exe + applyloop.cmd shim)"
    Write-Host "  - %USERPROFILE%\.autoapply\workspace\.api-token"
    Write-Host ""
    Write-Host "PRESERVES: ~/.autoapply (your job database, resumes, screenshots)."
    Write-Host "Pass -Force to skip this prompt."
    `$reply = Read-Host "Continue? (y/N)"
    if (`$reply -notmatch '^[Yy]') { Write-Host "Cancelled."; exit 0 }
}
Write-Host "[uninstall] Removing Task Scheduler entry..."
schtasks /Delete /TN ApplyLoopUpdate /F 2>&1 | Out-Null
Write-Host "[uninstall] Removing installed code at $ApplyloopHome..."
Remove-Item -Recurse -Force '$ApplyloopHome' -ErrorAction SilentlyContinue
Write-Host "[uninstall] Removing .exe + shim at $LocalBinDir..."
Remove-Item -Recurse -Force '$LocalBinDir' -ErrorAction SilentlyContinue
Write-Host "[uninstall] Removing Start Menu + Desktop shortcuts..."
`$startLnk   = Join-Path `$env:APPDATA 'Microsoft\Windows\Start Menu\Programs\ApplyLoop.lnk'
`$desktopLnk = Join-Path ([System.Environment]::GetFolderPath('Desktop')) 'ApplyLoop.lnk'
Remove-Item `$startLnk, `$desktopLnk -Force -ErrorAction SilentlyContinue
`$tokenFile = Join-Path `$env:USERPROFILE '.autoapply\workspace\.api-token'
if (Test-Path `$tokenFile) {
    Write-Host "[uninstall] Removing API token..."
    Remove-Item `$tokenFile -ErrorAction SilentlyContinue
}
Write-Host ""
Write-Host "Uninstalled. Workspace preserved at %USERPROFILE%\.autoapply"
Write-Host "(applications.db, resumes/, screenshots/ — delete manually if you want a clean slate)"
Write-Host ""
Write-Host "Optional: also uninstall global npm packages:"
Write-Host "  npm uninstall -g openclaw"
Write-Host "  npm uninstall -g @anthropic-ai/claude-code"
"@
Write-Utf8NoBom -Path $UninstallScript -Content $UninstallScriptContent
Write-Log "Uninstall script → $UninstallScript"

# Shim that dispatches on first arg:
#   applyloop          → launch the .exe (default)
#   applyloop start    → launch the .exe
#   applyloop update   → run update.ps1
#   applyloop uninstall → run uninstall.ps1 (interactive prompt)
#   applyloop version  → cat .applyloop-version
if ($ExePath) {
    $exeFullPath = $ExePath.FullName
    Write-ApplyloopShim `
        -LocalBinDir $LocalBinDir `
        -ApplyloopHome $ApplyloopHome `
        -ExePath $exeFullPath `
        -UpdateScript $UpdateScript `
        -UninstallScript $UninstallScript
    Write-Log "CLI shim → $LocalBinDir\applyloop.cmd (+ applyloop-update.cmd, applyloop-uninstall.cmd)"

    # ─── Start Menu + Desktop shortcuts ─────────────────────────────────
    # Without these, the user has to dig through %LOCALAPPDATA%\Programs to
    # find ApplyLoop.exe — there's no Win-key-then-type-ApplyLoop. Create
    # a .lnk so the Start menu indexes it and a desktop shortcut so first-
    # time users see exactly the same "click an icon to launch" affordance
    # they'd get on macOS from /Applications/ApplyLoop.app.
    try {
        $iconCandidate = Join-Path $ApplyloopHome "packages\desktop\icon.ico"
        if (-not (Test-Path $iconCandidate)) {
            $iconCandidate = $exeFullPath  # PyInstaller embeds the .exe icon
        }
        $startMenuDir  = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs"
        $startLnk      = Join-Path $startMenuDir "ApplyLoop.lnk"
        $desktopLnk    = Join-Path ([System.Environment]::GetFolderPath("Desktop")) "ApplyLoop.lnk"
        $wsh           = New-Object -ComObject WScript.Shell
        foreach ($lnk in @($startLnk, $desktopLnk)) {
            $shortcut                  = $wsh.CreateShortcut($lnk)
            $shortcut.TargetPath       = $exeFullPath
            $shortcut.WorkingDirectory = Split-Path $exeFullPath -Parent
            $shortcut.IconLocation     = $iconCandidate
            $shortcut.Description      = "ApplyLoop — automated job-application desktop app"
            $shortcut.Save()
        }
        Write-Log "Start Menu + Desktop shortcuts created (search for 'ApplyLoop' from Start)"
    } catch {
        Write-Warn "Could not create Start Menu/Desktop shortcut: $_"
    }
} else {
    Write-Warn ".exe build did not produce ApplyLoop.exe at expected path; CLI shim skipped"
}

# Add LocalBinDir to user PATH (idempotent)
$userPath = [System.Environment]::GetEnvironmentVariable("PATH", "User")
if (-not ($userPath -split ";" | Where-Object { $_ -eq $LocalBinDir })) {
    Write-Log "Adding $LocalBinDir to user PATH"
    $newPath = if ($userPath) { "$userPath;$LocalBinDir" } else { $LocalBinDir }
    [System.Environment]::SetEnvironmentVariable("PATH", $newPath, "User")
    $env:PATH = "$env:PATH;$LocalBinDir"
}

# Version stamp
$version = git -C $ApplyloopHome rev-parse HEAD 2>$null
if ($version) {
    Set-Content -Path (Join-Path $ApplyloopHome ".applyloop-version") -Value $version -Encoding UTF8
}

# ─── Phase K: Auto-update Task Scheduler ───────────────────────────────────
# Point the daily task DIRECTLY at update.ps1, not at the shim. The shim
# would also work but adds an extra cmd.exe → powershell.exe hop. Direct
# is one less moving part.
Write-Log "Registering daily auto-update task (3 AM)"
# Wrap the whole block in a local SilentlyContinue + try/catch so a schtasks
# failure (e.g. non-elevated shell → "Access is denied" on the system-scope
# task store) doesn't terminate the install. The install itself is complete
# by this point — .exe built, shortcuts placed, CLI shim wired. The auto-
# update task is a nice-to-have; the user can always rerun the install or
# manually run `applyloop update` to grab new versions.
$prevEAP = $ErrorActionPreference
$ErrorActionPreference = "SilentlyContinue"
$taskRegistered = $false
try {
    cmd /c "schtasks /Delete /TN ApplyLoopUpdate /F" 2>$null | Out-Null
    $updateCmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$UpdateScript`""
    # cmd /c bypasses PowerShell's "stderr → terminating error" coupling
    # under $ErrorActionPreference=Stop, so schtasks's normal stderr chatter
    # never trips the install. We rely on the exit code for the truth.
    cmd /c "schtasks /Create /TN ApplyLoopUpdate /TR `"$updateCmd`" /SC DAILY /ST 03:00 /F" 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) { $taskRegistered = $true }
} catch {
    # Intentionally swallow; we report via $taskRegistered below.
}
$ErrorActionPreference = $prevEAP
if ($taskRegistered) {
    Write-Log "  Daily 3 AM update task registered → $UpdateScript"
} else {
    Write-Warn "  Task Scheduler registration skipped (likely non-elevated shell)."
    Write-Warn "  Auto-updates won't run nightly, but everything else works."
    Write-Warn "  To enable: open PowerShell as Administrator, then run:"
    Write-Warn "    schtasks /Create /TN ApplyLoopUpdate /TR `"powershell.exe -NoProfile -ExecutionPolicy Bypass -File '$UpdateScript'`" /SC DAILY /ST 03:00 /F"
    Write-Warn "  Or just run 'applyloop update' manually whenever you want the latest version."
}

# ─── Success ─────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ApplyLoop installed successfully" -ForegroundColor Green
Write-Host ""
Write-Host "  Location: $ApplyloopHome"
Write-Host "  Workspace: $WorkspaceDir"
Write-Host "  CLI shim: $ShimPath"
if ($version) { Write-Host "  Version: $($version.Substring(0,12))" }
Write-Host ""
Write-Host "  Next steps:"
if ($ExePath) {
    Write-Host "    1. Launch the app: " -NoNewline
    Write-Host "$($ExePath.FullName)" -ForegroundColor Blue
}
Write-Host "    2. Or from any new PowerShell: " -NoNewline
Write-Host "applyloop start" -ForegroundColor Blue
Write-Host ""
Write-Host "  Update later:    " -NoNewline; Write-Host "applyloop update" -ForegroundColor Blue
Write-Host "  Daily 3 AM auto-update task: ApplyLoopUpdate (Task Scheduler)"
Write-Host ""
